### ISSUE TITLE
Please add a screen shot and consider renaming the repository

### ISSUE THREAD

**Issue by unixorn** [vzambon/vszambon_ocean-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.
Also, the repository name `zsh-theme` is awfully generic. Please consider renaming it to something descriptive, or even just name it `vszambon_ocean.zsh-theme` after the plugin

Thanks!

**Comment by vzambon** [comment]
Hi Joe,

Thank you for the feedback! I’ll make sure to add screenshots and a
description. I also agree that the repository name could be more
descriptive, so I’ll rename it.

I’ll update the repository accordingly and let you know once the changes
are made.

Best regards,
Vítor

**Comment by vzambon** [comment]
@unixorn I’ve made the updates as requested. The repository now includes a screenshot and a description, and I’ve renamed it to vszambon_ocean-zsh-theme.

If you have any further suggestions or feedback, please feel free to share. I’m open to any new ideas!

Thanks again for your input.
